SET FOREIGN_KEY_CHECKS=0;
DROP TABLE COMPANY
DROP TABLE Company_TYPESCERTIFICATE
DROP TABLE EVENT
DROP TABLE Event_DATES
DROP TABLE INDIVIDUALTICKET
DROP TABLE PASSTICKET
DROP TABLE PASSTICKET_INDIVIDUALTICKET
DROP TABLE RESERVATION
DROP TABLE RESERVATION_TICKET
DROP TABLE SEAT
DROP TABLE SEQUENCE
DROP TABLE TICKET
DROP TABLE TICKET_TICKET
DROP TABLE VENUE
DROP TABLE VENUE_SEAT