INSERT INTO COMPANY (ID, NUMBER) VALUES (1, 1)
INSERT INTO COMPANY (ID, NUMBER) VALUES (2, 2)
INSERT INTO Company_TYPESCERTIFICATE(Company_ID, TYPESCERTIFICATE) VALUES (1, 'TETEATETE')
INSERT INTO Company_TYPESCERTIFICATE(Company_ID, TYPESCERTIFICATE) VALUES (1, 'BANDOSENTADO')
INSERT INTO Company_TYPESCERTIFICATE(Company_ID, TYPESCERTIFICATE) VALUES (2, 'BANDOSENTADO')
INSERT INTO Company_TYPESCERTIFICATE(Company_ID, TYPESCERTIFICATE) VALUES (2, 'MULTIDAOEMPE')

